plugin:
  id: spectronaut-curtainptm-converter
  name: Spectronaut to CurtainPTM Converter
  description: Convert Spectronaut PTM output to CurtainPTM upload format. Supports multiple processing modes for different data formats - basic PTM processing, PTM group processing with site probabilities, and ProForma sequence processing with position validation.
  version: 1.0.0
  author: CauldronGO Team
  category: utilities
  subcategory: format-conversion
  icon: transform
  repository: https://github.com/noatgnu/spectronaut-curtainptm-converter-plugin

runtime:
  environments:
    - python
  entrypoint: convert.py

inputs:
  - name: input_file
    label: Spectronaut Output File
    type: file
    required: true
    accept: .txt,.tsv
    description: Spectronaut PTM output file containing differential analysis data

  - name: index_col
    label: Index Column Name
    type: text
    required: true
    default: PTM_collapse_key
    placeholder: PTM_collapse_key
    description: Column name containing position information in the format *_*X123_* where X is the residue and 123 is the position

  - name: peptide_col
    label: Peptide Column Name
    type: text
    required: true
    default: PEP.StrippedSequence
    placeholder: PEP.StrippedSequence
    description: Column name containing peptide sequences (format depends on processing mode)

  - name: uniprot_id_col
    label: UniProt ID Column Name
    type: text
    required: false
    default: UniprotID
    placeholder: UniprotID
    description: Column name containing UniProt accession IDs

  - name: processing_mode
    label: Processing Mode
    type: select
    required: true
    default: '1'
    options:
      - '1'
      - '2'
      - '3'
    description: |
      Processing mode selection:
      Mode 1: Basic PTM processing with position extraction from index column
      Mode 2: PTM group processing with site probability calculations
      Mode 3: ProForma sequence processing with enhanced position validation

  - name: modification_type
    label: Modification Type (Modes 2 & 3)
    type: text
    required: false
    default: Phospho (STY)
    placeholder: Phospho (STY)
    description: Type of modification to process (e.g., Phospho (STY), Acetyl (K), Methyl (K)). Only used in modes 2 and 3.
    visibleWhen:
      field: processing_mode
      equalsAny:
        - '2'
        - '3'

  - name: fasta_file
    label: FASTA File (Optional)
    type: file
    required: false
    accept: .fasta,.fa
    description: Protein sequence FASTA file. If not provided, sequences will be fetched from UniProt automatically.

  - name: uniprot_columns
    label: UniProt Data Columns
    type: text
    required: false
    default: accession,id,sequence,protein_name
    placeholder: accession,id,sequence,protein_name
    description: Comma-separated list of UniProt columns to retrieve when fetching sequences online

  - name: output_filename
    label: Output Filename
    type: text
    required: false
    default: curtainptm_input.txt
    placeholder: curtainptm_input.txt
    description: Name of the output file (will be created in the output folder)

  - name: sequence_window_size
    label: Sequence Window Size
    type: number
    required: false
    default: 21
    min: 1
    max: 101
    step: 2
    description: Size of the sequence window around modification sites (must be odd number). Default is 21 (10 residues before + modification + 10 after).

outputs:
  - name: converted_file
    path: '*.txt'
    type: data
    format: tsv
    description: Converted file in CurtainPTM upload format with PTM positions, sequence windows, and protein annotations

execution:
  outputDir: --output_folder
  requirements:
    pythonRequirementsFile: requirements.txt
    python: '>=3.10'
